/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { YesNoEnum } from './yes-no-enum';
 /**
 * 
 *
 * @export
 * @interface AddConfigInput
 */
export interface AddConfigInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof AddConfigInput
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof AddConfigInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof AddConfigInput
     */
    isDelete?: boolean;

    /**
     * 名称
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    name: string;

    /**
     * 编码
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    code?: string | null;

    /**
     * 参数值
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    value?: string | null;

    /**
     * @type {YesNoEnum}
     * @memberof AddConfigInput
     */
    sysFlag?: YesNoEnum;

    /**
     * 分组编码
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    groupCode?: string | null;

    /**
     * 排序
     *
     * @type {number}
     * @memberof AddConfigInput
     */
    orderNo?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof AddConfigInput
     */
    remark?: string | null;
}
