/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 查询匹配输出（F2）
 *
 * @export
 * @interface AllocateOutput
 */
export interface AllocateOutput {

    /**
     * 系统订单号
     *
     * @type {string}
     * @memberof AllocateOutput
     */
    orderNo?: string | null;

    /**
     * 收款类型
     *
     * @type {string}
     * @memberof AllocateOutput
     */
    type?: string | null;

    /**
     * 收款账号 / 二维码内容
     *
     * @type {string}
     * @memberof AllocateOutput
     */
    accountInfo?: string | null;

    /**
     * 收款码图片的根相对路径。无图时为空字符串。
     *
     * @type {string}
     * @memberof AllocateOutput
     */
    qrImageUrl?: string | null;

    /**
     * 请求金额
     *
     * @type {number}
     * @memberof AllocateOutput
     */
    requestAmount?: string;

    /**
     * 过期时间
     *
     * @type {Date}
     * @memberof AllocateOutput
     */
    expireTime?: Date;

    /**
     * 是否命中幂等键（true 表示该 ExternalNo 已有订单，本次未重新匹配）
     *
     * @type {boolean}
     * @memberof AllocateOutput
     */
    idempotentHit?: boolean;
}
