/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 用户表格列配置输出参数
 *
 * @export
 * @interface ColumnCustomOutput
 */
export interface ColumnCustomOutput {

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof ColumnCustomOutput
     */
    userId?: number;

    /**
     * 表格Id
     *
     * @type {string}
     * @memberof ColumnCustomOutput
     */
    gridId?: string | null;

    /**
     * 冻结列状态数据
     *
     * @type {{ [key: string]: string; }}
     * @memberof ColumnCustomOutput
     */
    fixedData?: { [key: string]: string; } | null;

    /**
     * 列宽状态数据
     *
     * @type {{ [key: string]: number; }}
     * @memberof ColumnCustomOutput
     */
    resizableData?: { [key: string]: number; } | null;

    /**
     * 列顺序数据
     *
     * @type {{ [key: string]: number; }}
     * @memberof ColumnCustomOutput
     */
    sortData?: { [key: string]: number; } | null;

    /**
     * 显示/隐藏列状态数据
     *
     * @type {{ [key: string]: boolean; }}
     * @memberof ColumnCustomOutput
     */
    visibleData?: { [key: string]: boolean; } | null;
}
