/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * GPU信息
 *
 * @export
 * @interface GpuInfo
 */
export interface GpuInfo {

    /**
     * GPU名称
     *
     * @type {string}
     * @memberof GpuInfo
     */
    name?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof GpuInfo
     */
    description?: string | null;

    /**
     * 厂商
     *
     * @type {string}
     * @memberof GpuInfo
     */
    vendor?: string | null;

    /**
     * 设备ID
     *
     * @type {string}
     * @memberof GpuInfo
     */
    deviceId?: string | null;

    /**
     * 总线信息
     *
     * @type {string}
     * @memberof GpuInfo
     */
    busInfo?: string | null;

    /**
     * 驱动版本
     *
     * @type {string}
     * @memberof GpuInfo
     */
    driverVersion?: string | null;

    /**
     * 显存大小（字节）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    memoryBytes?: number;

    /**
     * GPU温度（°C）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    temperature?: number | null;

    /**
     * 视频模式描述
     *
     * @type {string}
     * @memberof GpuInfo
     */
    videoModeDescription?: string | null;

    /**
     * 状态
     *
     * @type {string}
     * @memberof GpuInfo
     */
    status?: string | null;

    /**
     * GPU使用率（%）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    utilizationPercentage?: number | null;

    /**
     * 显存使用率（%）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    memoryUtilizationPercentage?: number | null;
}
