/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PayAccountStatusEnum } from './pay-account-status-enum';
 /**
 * 收款账号输出
 *
 * @export
 * @interface PayAccountOutput
 */
export interface PayAccountOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof PayAccountOutput
     */
    id?: number;

    /**
     * 收款类型标签
     *
     * @type {string}
     * @memberof PayAccountOutput
     */
    type?: string | null;

    /**
     * 账号信息（前后台均不脱敏，见设计决策）
     *
     * @type {string}
     * @memberof PayAccountOutput
     */
    accountInfo?: string | null;

    /**
     * 收款码图片的根相对路径。无图时为空字符串。
     *
     * @type {string}
     * @memberof PayAccountOutput
     */
    qrImageUrl?: string | null;

    /**
     * 总额度
     *
     * @type {number}
     * @memberof PayAccountOutput
     */
    totalQuota?: number;

    /**
     * 已用额度
     *
     * @type {number}
     * @memberof PayAccountOutput
     */
    usedQuota?: number;

    /**
     * 锁定中额度
     *
     * @type {number}
     * @memberof PayAccountOutput
     */
    lockedQuota?: number;

    /**
     * 剩余可用额度（计算得出）
     *
     * @type {number}
     * @memberof PayAccountOutput
     */
    remainingQuota?: number;

    /**
     * @type {PayAccountStatusEnum}
     * @memberof PayAccountOutput
     */
    status?: PayAccountStatusEnum;

    /**
     * 状态名称
     *
     * @type {string}
     * @memberof PayAccountOutput
     */
    statusText?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof PayAccountOutput
     */
    remark?: string | null;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof PayAccountOutput
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof PayAccountOutput
     */
    updateTime?: Date | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof PayAccountOutput
     */
    createUserName?: string | null;
}
