/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 业务操作审计动作枚举（F7.3，审计流水只增不改）<br />&nbsp;新增收款账号 AccountAdd = 1<br />&nbsp;编辑收款账号 AccountUpdate = 2<br />&nbsp;追加额度 QuotaAdd = 3<br />&nbsp;变更账号状态 StatusChange = 4<br />&nbsp;删除收款账号 AccountDelete = 5<br />&nbsp;异常到账处理 AbnormalHandle = 6<br />&nbsp;数据导出 Export = 7<br />&nbsp;开放接口调用 ApiCall = 8<br />&nbsp;开放接口认证失败 ApiAuthFailure = 9<br />
 * @export
 * @enum {string}
 */
export enum PayAuditActionEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9
}

