/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PayEventTypeEnum } from './pay-event-type-enum';
import { PayOrderStatusEnum } from './pay-order-status-enum';
 /**
 * 订单事件流水输出（F7.1 / F7.4）
 *
 * @export
 * @interface PayOrderEventOutput
 */
export interface PayOrderEventOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof PayOrderEventOutput
     */
    id?: number;

    /**
     * @type {PayEventTypeEnum}
     * @memberof PayOrderEventOutput
     */
    eventType?: PayEventTypeEnum;

    /**
     * 事件类型中文描述
     *
     * @type {string}
     * @memberof PayOrderEventOutput
     */
    eventTypeText?: string | null;

    /**
     * @type {PayOrderStatusEnum}
     * @memberof PayOrderEventOutput
     */
    fromStatus?: PayOrderStatusEnum;

    /**
     * 变更前状态中文描述
     *
     * @type {string}
     * @memberof PayOrderEventOutput
     */
    fromStatusText?: string | null;

    /**
     * @type {PayOrderStatusEnum}
     * @memberof PayOrderEventOutput
     */
    toStatus?: PayOrderStatusEnum;

    /**
     * 变更后状态中文描述
     *
     * @type {string}
     * @memberof PayOrderEventOutput
     */
    toStatusText?: string | null;

    /**
     * 本次事件涉及金额
     *
     * @type {number}
     * @memberof PayOrderEventOutput
     */
    amount?: number;

    /**
     * 事件发生后的累计到账金额
     *
     * @type {number}
     * @memberof PayOrderEventOutput
     */
    receivedTotal?: number;

    /**
     * 说明
     *
     * @type {string}
     * @memberof PayOrderEventOutput
     */
    remark?: string | null;

    /**
     * 操作人Id（系统事件为空）
     *
     * @type {number}
     * @memberof PayOrderEventOutput
     */
    operatorId?: number | null;

    /**
     * 操作人姓名（系统事件为空）
     *
     * @type {string}
     * @memberof PayOrderEventOutput
     */
    operatorName?: string | null;

    /**
     * 事件发生时间
     *
     * @type {Date}
     * @memberof PayOrderEventOutput
     */
    createTime?: Date;
}
