/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 订单事件类型枚举（F7.1 / F7.4，流水只增不改）<br />&nbsp;订单创建 Created = 1<br />&nbsp;部分到账 PartialReceived = 2<br />&nbsp;订单完成 Completed = 3<br />&nbsp;订单过期 Expired = 4<br />&nbsp;人工关联 ManualLinked = 5<br />
 * @export
 * @enum {string}
 */
export enum PayEventTypeEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5
}

