/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PayAccountOutput } from './pay-account-output';
 /**
 * 分页泛型集合
 *
 * @export
 * @interface SqlSugarPagedListPayAccountOutput
 */
export interface SqlSugarPagedListPayAccountOutput {

    /**
     * 页码
     *
     * @type {number}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    page?: number;

    /**
     * 页容量
     *
     * @type {number}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    pageSize?: number;

    /**
     * 总条数
     *
     * @type {number}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    total?: number;

    /**
     * 总页数
     *
     * @type {number}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    totalPages?: number;

    /**
     * 当前页集合
     *
     * @type {Array<PayAccountOutput>}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    items?: Array<PayAccountOutput> | null;

    /**
     * 是否有上一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    hasPrevPage?: boolean;

    /**
     * 是否有下一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    hasNextPage?: boolean;

    /**
     * 统计数据
     *
     * @type {any}
     * @memberof SqlSugarPagedListPayAccountOutput
     */
    totalInfo?: any | null;
}
