/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysCodeGenColumn } from './sys-code-gen-column';
 /**
 * 代码生成关联表
 *
 * @export
 * @interface SysCodeGenTable
 */
export interface SysCodeGenTable {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysCodeGenTable
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysCodeGenTable
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SysCodeGenTable
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysCodeGenTable
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SysCodeGenTable
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof SysCodeGenTable
     */
    isDelete?: boolean;

    /**
     * 代码生成Id
     *
     * @type {number}
     * @memberof SysCodeGenTable
     */
    codeGenId: number;

    /**
     * 数据库配置id
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    configId?: string | null;

    /**
     * 数据库表名
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    tableName?: string | null;

    /**
     * 表实体名称
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    entityName?: string | null;

    /**
     * 模块名称
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    moduleName?: string | null;

    /**
     * 业务名
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    busName?: string | null;

    /**
     * 上级联表字段
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    lastLinkPropertyName?: string | null;

    /**
     * 下级联表字段
     *
     * @type {string}
     * @memberof SysCodeGenTable
     */
    nextLinkPropertyName?: string | null;

    /**
     * 关联字段
     *
     * @type {Array<SysCodeGenColumn>}
     * @memberof SysCodeGenTable
     */
    columnList?: Array<SysCodeGenColumn> | null;
}
