/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HttpStatusCode } from './http-status-code';
import { YesNoEnum } from './yes-no-enum';
 /**
 * Http请求日志表
 *
 * @export
 * @interface SysLogHttp
 */
export interface SysLogHttp {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysLogHttp
     */
    id?: number;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof SysLogHttp
     */
    tenantId?: number | null;

    /**
     * 客户端名称
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    httpClientName?: string | null;

    /**
     * 接口描述
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    httpApiDesc?: string | null;

    /**
     * 请求方式
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    httpMethod?: string | null;

    /**
     * @type {YesNoEnum}
     * @memberof SysLogHttp
     */
    isSuccessStatusCode?: YesNoEnum;

    /**
     * 模块名称
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    actionName?: string | null;

    /**
     * 请求地址
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    requestUrl?: string | null;

    /**
     * 请求头
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    requestHeaders?: string | null;

    /**
     * 请求体
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    requestBody?: string | null;

    /**
     * 请求体明文
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    requestBodyPlaintext?: string | null;

    /**
     * @type {HttpStatusCode}
     * @memberof SysLogHttp
     */
    statusCode?: HttpStatusCode;

    /**
     * 响应头
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    responseHeaders?: string | null;

    /**
     * 响应体
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    responseBody?: string | null;

    /**
     * 响应体明文
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    responseBodyPlaintext?: string | null;

    /**
     * 异常信息
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    exception?: string | null;

    /**
     * 开始时间
     *
     * @type {Date}
     * @memberof SysLogHttp
     */
    startTime?: Date | null;

    /**
     * 结束时间
     *
     * @type {Date}
     * @memberof SysLogHttp
     */
    endTime?: Date | null;

    /**
     * 耗时（毫秒）
     *
     * @type {number}
     * @memberof SysLogHttp
     */
    elapsed?: number | null;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysLogHttp
     */
    createTime?: Date;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysLogHttp
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysLogHttp
     */
    createUserName?: string | null;
}
