<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <PublishReadyToRunComposite>true</PublishReadyToRunComposite>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <UserSecretsId>ad9369d1-f29b-4f8f-a7df-8b4d7aa0726b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>
    <Copyright>Admin.NET</Copyright>
    <Description>Admin.NET 通用权限开发平台</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="logs\**" />
    <Compile Remove="publish\**" />
    <Compile Remove="wwwroot\template_debug\**" />
    <Content Remove="wwwroot\template_debug\**" />
    <EmbeddedResource Remove="logs\**" />
    <EmbeddedResource Remove="publish\**" />
    <EmbeddedResource Remove="wwwroot\template_debug\**" />
    <None Remove="logs\**" />
    <None Remove="publish\**" />
    <None Remove="wwwroot\template_debug\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\avatar\**" CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\template\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="ip2region.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="sensitive-words.txt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\upload\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Admin.NET.Web.Core\Admin.NET.Web.Core.csproj" />
  </ItemGroup>

</Project>
