/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddPayAccountInput } from '../models';
import { AddQuotaInput } from '../models';
import { AdminNETResultInt64 } from '../models';
import { AdminNETResultListPayTypeOption } from '../models';
import { AdminNETResultPayAccountOutput } from '../models';
import { AdminNETResultSqlSugarPagedListPayAccountOutput } from '../models';
import { BaseIdInput } from '../models';
import { PagePayAccountInput } from '../models';
import { SetPayAccountStatusInput } from '../models';
import { UpdatePayAccountInput } from '../models';
/**
 * PayAccountApi - axios parameter creator
 * @export
 */
export const PayAccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 新增收款账号/收款码（F1.1）
         * @param {AddPayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountAddPost: async (body?: AddPayAccountInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payAccount/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = localVarRequestOptions.headers || {};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 追加后若账号处于「已用完」且剩余额度恢复为正数，自动回置为「启用」重新参与匹配（F1.4）。
         * @summary 追加总额度（F1.2）
         * @param {AddQuotaInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountAddQuotaPost: async (body?: AddQuotaInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payAccount/addQuota`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = localVarRequestOptions.headers || {};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 存在未终结订单（待到账/部分到账）时禁止删除，避免订单悬挂。
         * @summary 删除收款账号
         * @param {BaseIdInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountDeletePost: async (body?: BaseIdInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payAccount/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = localVarRequestOptions.headers || {};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 返回完整账号信息（前后台均不脱敏，见设计决策）。
         * @summary 获取收款账号详情
         * @param {number} id 主键Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountDetailPost: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiPayAccountDetailPost.');
            }
            const localVarPath = `/api/payAccount/detail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (id !== undefined) {
                localVarQueryParameter['Id'] = id;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 按设计决策（2026-09-16）：前后台均**不脱敏**，列表返回完整账号信息， 以便管理员核对与维护账号。账号明文的保护由接口签名鉴权 + 后台 RBAC 承担。
         * @summary 获取收款账号分页列表（F1.5）
         * @param {PagePayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountPagePost: async (body?: PagePayAccountInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payAccount/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = localVarRequestOptions.headers || {};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 启用/停用收款账号（F1.3）
         * @param {SetPayAccountStatusInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountSetStatusPost: async (body?: SetPayAccountStatusInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payAccount/setStatus`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = localVarRequestOptions.headers || {};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取收款类型下拉列表（取字典 pay_account_type）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountTypeOptionsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payAccount/typeOptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 编辑收款账号（F1.2：修改备注、状态）
         * @param {UpdatePayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPayAccountUpdatePost: async (body?: UpdatePayAccountInput, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payAccount/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = localVarRequestOptions.headers || {};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PayAccountApi - functional programming interface
 * @export
 */
export const PayAccountApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 新增收款账号/收款码（F1.1）
         * @param {AddPayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountAddPost(body?: AddPayAccountInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminNETResultInt64>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountAddPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 追加后若账号处于「已用完」且剩余额度恢复为正数，自动回置为「启用」重新参与匹配（F1.4）。
         * @summary 追加总额度（F1.2）
         * @param {AddQuotaInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountAddQuotaPost(body?: AddQuotaInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountAddQuotaPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 存在未终结订单（待到账/部分到账）时禁止删除，避免订单悬挂。
         * @summary 删除收款账号
         * @param {BaseIdInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountDeletePost(body?: BaseIdInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountDeletePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 返回完整账号信息（前后台均不脱敏，见设计决策）。
         * @summary 获取收款账号详情
         * @param {number} id 主键Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountDetailPost(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminNETResultPayAccountOutput>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountDetailPost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 按设计决策（2026-09-16）：前后台均**不脱敏**，列表返回完整账号信息， 以便管理员核对与维护账号。账号明文的保护由接口签名鉴权 + 后台 RBAC 承担。
         * @summary 获取收款账号分页列表（F1.5）
         * @param {PagePayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountPagePost(body?: PagePayAccountInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminNETResultSqlSugarPagedListPayAccountOutput>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountPagePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 启用/停用收款账号（F1.3）
         * @param {SetPayAccountStatusInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountSetStatusPost(body?: SetPayAccountStatusInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountSetStatusPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取收款类型下拉列表（取字典 pay_account_type）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountTypeOptionsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminNETResultListPayTypeOption>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountTypeOptionsGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 编辑收款账号（F1.2：修改备注、状态）
         * @param {UpdatePayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountUpdatePost(body?: UpdatePayAccountInput, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PayAccountApiAxiosParamCreator(configuration).apiPayAccountUpdatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PayAccountApi - factory interface
 * @export
 */
export const PayAccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 新增收款账号/收款码（F1.1）
         * @param {AddPayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountAddPost(body?: AddPayAccountInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminNETResultInt64>> {
            return PayAccountApiFp(configuration).apiPayAccountAddPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 追加后若账号处于「已用完」且剩余额度恢复为正数，自动回置为「启用」重新参与匹配（F1.4）。
         * @summary 追加总额度（F1.2）
         * @param {AddQuotaInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountAddQuotaPost(body?: AddQuotaInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PayAccountApiFp(configuration).apiPayAccountAddQuotaPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 存在未终结订单（待到账/部分到账）时禁止删除，避免订单悬挂。
         * @summary 删除收款账号
         * @param {BaseIdInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountDeletePost(body?: BaseIdInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PayAccountApiFp(configuration).apiPayAccountDeletePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 返回完整账号信息（前后台均不脱敏，见设计决策）。
         * @summary 获取收款账号详情
         * @param {number} id 主键Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountDetailPost(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminNETResultPayAccountOutput>> {
            return PayAccountApiFp(configuration).apiPayAccountDetailPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 按设计决策（2026-09-16）：前后台均**不脱敏**，列表返回完整账号信息， 以便管理员核对与维护账号。账号明文的保护由接口签名鉴权 + 后台 RBAC 承担。
         * @summary 获取收款账号分页列表（F1.5）
         * @param {PagePayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountPagePost(body?: PagePayAccountInput, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminNETResultSqlSugarPagedListPayAccountOutput>> {
            return PayAccountApiFp(configuration).apiPayAccountPagePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 启用/停用收款账号（F1.3）
         * @param {SetPayAccountStatusInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountSetStatusPost(body?: SetPayAccountStatusInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PayAccountApiFp(configuration).apiPayAccountSetStatusPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取收款类型下拉列表（取字典 pay_account_type）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountTypeOptionsGet(options?: AxiosRequestConfig): Promise<AxiosResponse<AdminNETResultListPayTypeOption>> {
            return PayAccountApiFp(configuration).apiPayAccountTypeOptionsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 编辑收款账号（F1.2：修改备注、状态）
         * @param {UpdatePayAccountInput} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPayAccountUpdatePost(body?: UpdatePayAccountInput, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PayAccountApiFp(configuration).apiPayAccountUpdatePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PayAccountApi - object-oriented interface
 * @export
 * @class PayAccountApi
 * @extends {BaseAPI}
 */
export class PayAccountApi extends BaseAPI {
    /**
     * 
     * @summary 新增收款账号/收款码（F1.1）
     * @param {AddPayAccountInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountAddPost(body?: AddPayAccountInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminNETResultInt64>> {
        return PayAccountApiFp(this.configuration).apiPayAccountAddPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 追加后若账号处于「已用完」且剩余额度恢复为正数，自动回置为「启用」重新参与匹配（F1.4）。
     * @summary 追加总额度（F1.2）
     * @param {AddQuotaInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountAddQuotaPost(body?: AddQuotaInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PayAccountApiFp(this.configuration).apiPayAccountAddQuotaPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 存在未终结订单（待到账/部分到账）时禁止删除，避免订单悬挂。
     * @summary 删除收款账号
     * @param {BaseIdInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountDeletePost(body?: BaseIdInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PayAccountApiFp(this.configuration).apiPayAccountDeletePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 返回完整账号信息（前后台均不脱敏，见设计决策）。
     * @summary 获取收款账号详情
     * @param {number} id 主键Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountDetailPost(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminNETResultPayAccountOutput>> {
        return PayAccountApiFp(this.configuration).apiPayAccountDetailPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 按设计决策（2026-09-16）：前后台均**不脱敏**，列表返回完整账号信息， 以便管理员核对与维护账号。账号明文的保护由接口签名鉴权 + 后台 RBAC 承担。
     * @summary 获取收款账号分页列表（F1.5）
     * @param {PagePayAccountInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountPagePost(body?: PagePayAccountInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminNETResultSqlSugarPagedListPayAccountOutput>> {
        return PayAccountApiFp(this.configuration).apiPayAccountPagePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 启用/停用收款账号（F1.3）
     * @param {SetPayAccountStatusInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountSetStatusPost(body?: SetPayAccountStatusInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PayAccountApiFp(this.configuration).apiPayAccountSetStatusPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取收款类型下拉列表（取字典 pay_account_type）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountTypeOptionsGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminNETResultListPayTypeOption>> {
        return PayAccountApiFp(this.configuration).apiPayAccountTypeOptionsGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 编辑收款账号（F1.2：修改备注、状态）
     * @param {UpdatePayAccountInput} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayAccountApi
     */
    public async apiPayAccountUpdatePost(body?: UpdatePayAccountInput, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PayAccountApiFp(this.configuration).apiPayAccountUpdatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
